### ISSUE TITLE
SRegen will rebuild multi-chunk structures in nearby claimed chunks (if they are close enough)

### ISSUE THREAD

**Issue by Maxstripe** [StargateMC/StargateMCPublic#126]
Sregen partialy regens chunks on the nether world (i had a claim on a fortrtess and the fortress bits regenned in my land)

**Comment by DraksterAU** [comment]
SRegen doesn't do partial chunks.
Describe the issue in more detail.

**Comment by DraksterAU** [comment]
I'm going to add a "last regenerated" flag to chunks so this stops being something you guys jump at. You'll find the chunk wasn't regenerated haha.

**Comment by Maxstripe** [comment]
i claimed part of a nether fortress and tore it aparent and flattened it. the nether fortress walls came back in my claim

**Comment by DraksterAU** [comment]
Oh wow, I never noticed.
If another nearby chunk regenerates a multi-chunk structure will re-build in your claimed chunk.
I don't think I can fix this.... but will give it some thought.

**Comment by DraksterAU** [comment]
@Maxstripe Does this happen only when there is room in your chunk, or does it remove blocks from your land to do it?

**Comment by Maxstripe** [comment]
it removes blocks
damage has been fixed as of my last visit but it might have done it again (fixed it the other day)

**Comment by Maxstripe** [comment]
it has happened yet again
