### ISSUE TITLE
Some StargateMC Custom Items do not have lang entries

### ISSUE THREAD

**Issue by XredstonemodsX** [StargateMC/StargateMCPublic#137]
Any item that our dearest Bysokar has created show up as their unlocalized name in NEI and creative menus, whether because he has simply not added their localizations to the .lang files or some other reason, it's quite annoying, and a fix would be appreciated

**Comment by DraksterAU** [comment]
What localisation do you play with?
I only support En-US.

**Comment by DraksterAU** [comment]
It's still an issue..

**Comment by DraksterAU** [comment]
This is fixed
