### ISSUE TITLE
WarpDrive ships crash server if they warp with Advanced Solar Panels onboard

### ISSUE THREAD

**Issue by Maxstripe** [StargateMC/StargateMCPublic#14]
Rec bugged a ship on top of a redwood tree at -245 65 -238 and the chunk needs to be reset before him, cookie, or main can log back in 
No one can go threw the worlds main gate without getting stuck there

**Comment by recneps** [comment]
If you revert the dimension - or the chunks - to a backup from 8:00 MST on the fifteenth or before(as close to 8:00 as possible is best, to reduce chances of people losing work), it will be fine.

**Comment by DraksterAU** [comment]
The World has been reverted to restore it to working order.
I've also enabled Debug logs for WarpDrive.

In future: Please do not repeatedly log into the server if you logging into a corrupt world brings it down, it ruins n the gameplay experience for people not affected by the issue :)
