### ISSUE TITLE
getNetworkedStargate() method does not work properly

### ISSUE THREAD

**Issue by Maxstripe** [StargateMC/StargateMCPublic#142]
it throws the address, planet name and a set of cords
said set of cords are wrong in all gates except my space gate for some reason (it doesnt even throw the correct cords for the spawn gate)

**Comment by DraksterAU** [comment]
Coordinates are that Of the world in space - the only time that it will use the coords of the gate is in space

**Comment by DraksterAU** [comment]
Didn't wanna do coords on the world because it makes it too easy for snemies... I can if you guys would pref though

**Comment by Maxstripe** [comment]
ok thats fine. makes it so i can pull world cords and gate addreses from world easier
