### ISSUE TITLE
Portable Dialling Devices should instantly connect a wormhole, not trigger dialling 

### ISSUE THREAD

**Issue by Maxstripe** [StargateMC/StargateMCPublic#15]
basicly remmber that hand held asgaurd dialer thor had when he came to earth? the one that opened the gate without a woosh? yea one of those would be useful

**Comment by DraksterAU** [comment]
So basically portable diallers should handle all dialling and simply connect the wormhole at the end, with no dialling process?

**Comment by Maxstripe** [comment]
just the asgaurd one if we have multiple versions
pretty sure the asgaurd were the only ones to make this anyway...

**Comment by DraksterAU** [comment]
I'm not going to make an Asgard dialler - it will be generic and tiered.. But themed from the kino.

**Comment by Maxstripe** [comment]
ok

**Comment by DraksterAU** [comment]
Not going to do this one sorry man.
When I look at gate behaviour I will do it .
