### ISSUE TITLE
Some Power Armor recipes do not work.

### ISSUE THREAD

**Issue by PixelGamerX32** [StargateMC/StargateMCPublic#151]
Hi, I am trying to make parts for my power armor upgrades on StargateMC.com server but some recipes don't work properly.

For example, I look up the recipe in nei for a  MV capacitor which gives me this:
![stargatemc server recipe mv cap](https://cloud.githubusercontent.com/assets/21307676/18048394/b8f968f6-6dd9-11e6-974b-b2b336ca9f8f.PNG)
This shows that I need 1 golden ingot, 2 wiring, and any kind of blue dye (lapis, blue dye, etc.)
However when I try this recipe:
![stargatemc server recipe mv cap attempt](https://cloud.githubusercontent.com/assets/21307676/18048438/fd32d55c-6dd9-11e6-9cdf-6342e38c0654.PNG)
This shows I have placed them right. But cannot make the Item.
I have tried the original recipes. These don't work either.

This also applies to the HV capacitor.
However when I make the solenoids it works.

This is the recipe it shows:
![stargatemc server recipe solenoid](https://cloud.githubusercontent.com/assets/21307676/18048552/c90823c6-6dda-11e6-905a-32eb92f3a809.PNG)

And this gives the intended item:
![stargatemc server recipe solenoid attempt](https://cloud.githubusercontent.com/assets/21307676/18048573/d7dbddb6-6dda-11e6-9960-962524ef8fa7.PNG)

Overall, only some recipes are correct and work as intended.
Please can someone look into this. Thanks

**Comment by Maxstripe** [comment]
Recipes aren't broken
News display of them is. If you find the file with the recipies on github it will show working recipies

**Comment by DraksterAU** [comment]
This has now been resolved @Maxstripe @PixelGamerX32
