### ISSUE TITLE
Change Capacitive Crystal recipe to be more reasonable

### ISSUE THREAD

**Issue by Elanis** [StargateMC/StargateMCPublic#153]
The **Capacitive Crystal** Recipe need **Regeneration II potions** to craft it. It's not realist and ghast tears are very hard ( this mobs are already up to lava ^^ ).
Well, thats were cool to replace theses potions by other things. Other crystals need emerald, diamond or ender pearl so i suggest to use an **Energy Crystal** ( IC2 ) crafted with diamond dust and redstone instead of the potion. I'll be more realistic i think.

**Comment by Maxstripe** [comment]
how about lapotron crystals? cant make it too easy

**Comment by Elanis** [comment]
I said Energy Crystal because of the color but yes lapotron crystals is also a good idea.
