### ISSUE TITLE
Some Power Armor recipes are not correct.

### ISSUE THREAD

**Issue by PixelGamerX32** [StargateMC/StargateMCPublic#154]
Hi all.
I have noticed that some of the recipes use wrong items to create certain items. This makes it much harder to make these items.
For example, the wiring recipe should use 2 golden nuggets and 1 redstone dust:
![wiring recipe for mps mod](https://cloud.githubusercontent.com/assets/21307676/18093900/6a325318-6ec9-11e6-815c-2e8c2223e81d.PNG)
But on the server instead of golden nuggets, the ingot form of gold is used instead:
![wiring recipe for mps mod serverside](https://cloud.githubusercontent.com/assets/21307676/18094196/869ae672-6eca-11e6-8bdb-db32d9f1ad0e.PNG)
It used to be the first recipe.
This also applies to the MV capacitor where, again, the golden nugget should be used instead of a gold ingot.
![mv capacitor recipe for mps mod](https://cloud.githubusercontent.com/assets/21307676/18094223/a69cf8c0-6eca-11e6-90e3-37c86984be16.PNG)
The golden ingot in the recipe from picture below should be a golden nugget like above.
![mv capacitor recipe for mps mod from server](https://cloud.githubusercontent.com/assets/21307676/18094226/a8593dd6-6eca-11e6-9f94-02a74c3fd29f.PNG)
Please can someone look into this? Thanks

**Comment by DraksterAU** [comment]
Hi @PixelGamerX32, sorry but they made this one harder for a reason. I'm going to have to decline the request.
