### ISSUE TITLE
SGC Gate cannot Dial Midway

### ISSUE THREAD

**Issue by Elanis** [StargateMC/StargateMCPublic#156]
It says it need the 8th chevron upgrade.
Also the DHD is missing.

**Comment by DraksterAU** [comment]
Fixed by installing 8 chevron circuit upgrade in the OC computer interface on Earth.

**Comment by DraksterAU** [comment]
Ps every gate in the Milky Way shows up on the earth gate - so there will be no dhd going forward. Dial out and turn around and use a dhd off world if you really need to.

**Comment by Elanis** [comment]
Thanks !
