### ISSUE TITLE
Provide method of charging devices via ZPM when mobile

### ISSUE THREAD

**Issue by Maxstripe** [StargateMC/StargateMCPublic#16]
so basicly an interface item for a zpm that lets it charge all items in your inventory

**Comment by DraksterAU** [comment]
Max, can this not be done with an mfsu charging pad with a ZPM in it?

**Comment by Maxstripe** [comment]
it can be done with mfsu but some tech requires high juice and plugging in takes too much time for high level tech

**Comment by DraksterAU** [comment]
Ok fair enough. Is there no portable charger via Mekanism?

If there isn't we'll pop this in as a low priority request.

So you know, ZPMs will only go into the stargate power interface by default (which will transmit 32768EU
Per tick per side)

**Comment by DraksterAU** [comment]
ZPMs will not be able to be withdrawn from when on the move. 
As they are such a massive power source it will cause balance issues if things like a Quantum Armour suit can support them.

The "EU Power Interface" and "RF Power Interface" blocks will allow ZPMs to be withdrawn from at a high rate... but will require the interface be placed, first.

Sorry @Maxstripe.
