### ISSUE TITLE
Subspace Transceiver

### ISSUE THREAD

**Issue by Bysokar** [StargateMC/StargateMCPublic#160]
The Subspace transceivers will operate independently to a stargate computer interface.

This will allow connection to other transceivers throughout the universe to do the following;

- [ ] Send & Receive messages, optionally password protected
- [ ] Analyse the atmospheric data around them
- [ ] Provide their universal location information
- [ ] Provide viability sensors for whether or not the area is safe.
- [ ] Track life signs in the immediate area.

They will have a peak range of around 50% of the universe but require crude-zpm level amounts of power to operate at that level. The range will be configurable on the fly.

Computer methods supported;

 - [ ] **transceiver.getAtmosphereClassification()** : Will get the atmosphere classification of the planet, which when this is added will be removed from the stargate interface.
 - [ ] **transceiver.getCurrentWeather()**  : This will return the current weather on the planet. It will not succeed if the transceiver is in an area that is not exposed to the atmosphere.
 - [ ] **transceiver.getViability()**  : This will return the current habitability of the area around the gate. This will return entries like: RADIATIONFOUND, UNDERWATER, UNDERLAVA, VIABLE etc.
 - [ ] **transceiver.getLifeSignsNearby(range)** : This will scan the immediate area within the range value and list the coordinates of the entities it finds. Max range of 128 blocks in all directions.
 - [ ] **transceiver.sendMessage(msg, password, targetPos)** : This will send a message that is optionally encrypted with a password to the targetPosition. If no target Position is specified, it is a broadcast that will reduce the maximum range by 75%. If a target position is specified, the devices that are not in the path between source and destination will have a reduced chance of picking up the signal. Anything further away from the destination than the source is, will have no chance.
 - [ ] **transceiver.pollMessageBuffer(password)** : This will poll the buffer on the device for messages, decrypting them with the password if it can.
 - [ ] **transceiver.setPowerLevel(percentage)** : This will set the range and dial the power requirements up based on a % value. (eg: 100% = Max Power Drain & Max Range)

**Exact structure of this device is TBA.**

**Comment by Maxstripe** [comment]
i like it. add it in

**Comment by DraksterAU** [comment]
@maxstripe haha yeah. Low priority for now.
Most of this code is a kino without the moving parts - figured that I'd make something that behaves similarly before I dive into modelling a sphere and getting it to move
