### ISSUE TITLE
Connect path near the mines on lacun to the lodge at the top of the hill

### ISSUE THREAD

**Issue by Bysokar** [StargateMC/StargateMCPublic#179]
As above, the mines have a ring platform that needs to be not relied on..... it crashes certain players.

Not to mention the rings cant be used by NPCs without a great deal of work..

**Comment by mainesi** [comment]
I've done the two main areas of the rings to the gouald and the miners lodge. Will do the same for the under area later today

**Comment by DraksterAU** [comment]
Thanks @mainesi  :)

**Comment by DraksterAU** [comment]
@mainesi how have you done this bud?? Elevators are lame... :P

**Comment by mainesi** [comment]
Ok I'll create a path instead going into the cave system already created
