### ISSUE TITLE
Create Kino Remote (Tier 1 Remote Dialler)

### ISSUE THREAD

**Issue by DraksterAU** [StargateMC/StargateMCPublic#18]
Kino Remotes will have the following functionality:

- Shift + RightClick (Dial Stargate nearby if there is one to the selected address)
- RightClick (Cycle through the in-range stargates)
- Will NOT contain a power source that runs the gate, only itself
- Will not have support for dialling addresses outside the galaxy it is in
- Will not have support for dialling addresses when the user is not in a galaxy
- Will have a range of 30% of a galaxy. This means if a planet is on the opposite side of a galaxy it may not show up until you gate to a planet that is closer.

Recipe: TBC
Texture: TBC

Power Capacity: 50K EU
Power Per Use (Dial): 5K EU
Power Per Use (Cycle): 2K EU
Rechargable: Yes

**Comment by XredstonemodsX** [comment]
Dialing should cost more than simply cycling through the possible gates in range

**Comment by DraksterAU** [comment]
@XredstonemodsX The Tier 1 Kino Remote doesn't use its own power to dial a stargate. It relies on the power source connected to the gate.

Tier 2 and 3 support power :)

**Comment by DraksterAU** [comment]
Kino has been done. Ill work out tweaks later.
