### ISSUE TITLE
Create Portable DHD (Tier 2 Remote Dialler)

### ISSUE THREAD

**Issue by Bysokar** [StargateMC/StargateMCPublic#19]
Portable DHDs will have the following functionality:

- Shift + RightClick (Dial Stargate nearby if there is one to the selected address)
- RightClick (Cycle through the in-range stargates)
- Will contain a power source that runs the gate
- Will support addresses that require an 8 chevron upgrade
- Will have a range of 15% of the known universe (or whatever is defined in the SUniverse configuration as an 'immense distance' - which requires a 9 chevron upgrade).

Recipe: TBC
Texture: TBC

Power Capacity: 50M EU ~To be confirmed
Power Per Use (Dial): 5K EU + Dialling costs. 
Will use the stargates power if it is available before using the remote diallers.
Power Per Use (Cycle): 2K EU
Rechargable: Yes

**Comment by XredstonemodsX** [comment]
Dialing cost should cost more than the cycling costs
