### ISSUE TITLE
Suggestion - Restarts

### ISSUE THREAD

**Issue by XredstonemodsX** [StargateMC/StargateMCPublic#191]
I suggest adding a way to start the server back up from the site when it has crashed, this will only allow startups and if the server is currently running the button will either not be on the page, or it won't do anything

**Comment by mainesi** [comment]
Or even better only allow admins the ability to do that as I am always monitoring github and discord

**Comment by DraksterAU** [comment]
Last time I checked main had an mcma account, and so did a couple of others.

The problem with this is people jump at the restart button when the server is "running slowly" when a restart will not help them.

Ask for an mcma account if you don't have one or ask for a password reset next time I am on.
