### ISSUE TITLE
Idea: Announcing when certain items go on market.

### ISSUE THREAD

**Issue by XredstonemodsX** [StargateMC/StargateMCPublic#202]
Certain items such as the ZPM will only be on the market for a short time, I propose a config option on all market that allows you to enable announcing the item appearing on the market. Will not give price, location, or time left.

**Comment by Bysokar** [comment]
Agreed. Will add this soon.

**Comment by Bysokar** [comment]
@XredstonemodsX I'm thinking: 

- If Chance is below 50% and above 25%: Broadcast to world.
- If Chance is below 25% and above 5%: Broadcast to nearby worlds.
- If Chance is below 5%, broadcast to server.

**Comment by XredstonemodsX** [comment]
Sounds reasonable

**Comment by Bysokar** [comment]
This is done. 

Items with <= 0.2% will be considered ultra rare, 0.3% to 0.5% are rare, and 0.5% to 5% are uncommon.
