### ISSUE TITLE
Iris death glitch

### ISSUE THREAD

**Issue by dodhod** [StargateMC/StargateMCPublic#209]
Death message when being killed by Stargate Iris is something like: sgcraft.stargate.iris

**Comment by XredstonemodsX** [comment]
[en_US.txt](https://github.com/StargateMC/StargateMCPublic/files/491922/en_US.txt)
\
Updated US language file, Sokar just change file type to .lang when you put It in

**Comment by Bysokar** [comment]
Both of those are in the lang already (and your lang has not got all the options)

**Comment by XredstonemodsX** [comment]
They were missdefined in the lang, assuning it's meant to have put the exact message you get upon death in here. I'll copy paste the lines.

death.attack.sgcraft:transient.player=%1$s was torn apart by an event horizon
death.attack.sgcraft:iris.player=%1$s splattered against a stargate iris
