### ISSUE TITLE
[Forum] Requests for item added to the shop

### ISSUE THREAD

**Issue by XredstonemodsX** [StargateMC/StargateMCPublic#220]
Here is where you will make requests for items you wish to be put into the shop. The requests must include the ITEMID including meta data:

eg. 194:6 = Radioisotope Thermoelectric generator.

Do not post a suggestion more than once. Check all preivous suggestions and make sure yours is original, if you have any doubts about if I'm working on an item contact me on Discord

**Comment by Bysokar** [comment]
Please place this in the forums, players don't typically use GitHub all that often. 
http://www.stargatemc.com/?post_type=forum
