### ISSUE TITLE
Mod Suggestion: Thermal Dynamics

### ISSUE THREAD

**Issue by XredstonemodsX** [StargateMC/StargateMCPublic#23]
Thermal Dynamics is a mod that offers much in the way of Energy, Item, and Fluids transfer. It adds pipes which function much like the Mekanism mechanical pipes do, but also gives more room for automation, and are easier to use for some.

**Comment by DraksterAU** [comment]
This has been completed. I've updated Thermal Expansion etc while I am at it.
