### ISSUE TITLE
Issue with Srpg?

### ISSUE THREAD

**Issue by dodhod** [StargateMC/StargateMCPublic#232]
Moderator Maxstripe: well the first message works properly and says -30 sgc +10 goauld
Moderator Maxstripe: but the sprotect messages after say your loosing points with goauld

When Max attacks one of my SGC Npc's this happens ^. At first, without him giving me this info I though I'd set up the NPC facs wrong, but them two lines he gets contradict each other.. Leading me to believe its a glitch.

**Comment by Bysokar** [comment]
Screenshot.

**Comment by dodhod** [comment]
Fixed.

**Comment by Bysokar** [comment]
How is this fixed?

**Comment by dodhod** [comment]
It didn't need to be'fixed' I don't know why I said fixed should of said.. I know why now. The explanation I was given was the sgc and goauld being qllies. Guess that needs changing
