### ISSUE TITLE
New Client Load Screen

### ISSUE THREAD

**Issue by dodhod** [StargateMC/StargateMCPublic#234]
The logo for the server I made
![loadinggate_003](https://cloud.githubusercontent.com/assets/20968094/18814447/b0fc992e-830b-11e6-91f9-e5b9661ddfd8.jpg)

**Comment by Bysokar** [comment]
Happy to convert this to the client loading screen if you're interested. Just need to have it resized appropriately as a PNG - Ill do that when I figure out the exact resolution required.

**Comment by dodhod** [comment]
That would be nice :)

**Comment by PixelGamerX32** [comment]
This definetly looks good. Good choice.

**Comment by dodhod** [comment]
Thanks @PixelGamerX32
