### ISSUE TITLE
Idea: Stargate Change

### ISSUE THREAD

**Issue by dodhod** [StargateMC/StargateMCPublic#236]
In the TV show we always see stargates looking like
![images](https://cloud.githubusercontent.com/assets/20968094/18815918/c25d9126-8335-11e6-9675-8344699b6b01.jpeg)
With stairs going up to them (unless they have frozen over etc etc) I think we should change them to look like this. Here is an example I made:
![2016-09-23_09 57 02](https://cloud.githubusercontent.com/assets/20968094/18815926/080f9cc8-8336-11e6-877a-8907ee699e30.png)

**Comment by mainesi** [comment]
Nice idea but I wouldn't say the layout u have done is the best one.

A set of stairs with side parts and not stairs all round

**Comment by dodhod** [comment]
Thats why I said 'example' :P

**Comment by Bysokar** [comment]
We have many worlds, with many builds surrounding the stargate.
This isn't really a GitHub issue, its more of a suggestion on how to build one when we start increasing the world size (at least that is my understanding).
