### ISSUE TITLE
I've noticed the Stargate warning message has red text, except the word the.

### ISSUE THREAD

**Issue by dodhod** [StargateMC/StargateMCPublic#238]
![2016-09-25_12 21 00](https://cloud.githubusercontent.com/assets/20968094/18815934/51b058f4-8336-11e6-9263-77246e875c04.png)
Can this be changed so it's either all red or all white?

**Comment by XredstonemodsX** [comment]
[en_US.txt](https://github.com/StargateMC/StargateMCPublic/files/491921/en_US.txt)

Updated en._US.lang (Had to make text file for github to allow upload, just change the file from en_US.txt to en_US.lang)

**Comment by Bysokar** [comment]
This should be fixed in the latest update, please confirm and close.
