### ISSUE TITLE
Every time I log onto the server my skin appears as a steve (even though I have a set skin and it shows on other servers)

### ISSUE THREAD

**Issue by dodhod** [StargateMC/StargateMCPublic#239]
Even to other people my usual skin is still there, but to me its steve...
![2016-09-24_12 02 57](https://cloud.githubusercontent.com/assets/20968094/18815946/74830a98-8336-11e6-8b09-e829d8743090.png)

**Comment by Bysokar** [comment]
This isn't occurring for anyone else.... where is your skin hosted?

**Comment by dodhod** [comment]
'Hosted' Minecraft.com

**Comment by Bysokar** [comment]
Does this still happen?

**Comment by dodhod** [comment]
Yes
