### ISSUE TITLE
Mod Sugestion: Peripherals ++

### ISSUE THREAD

**Issue by Maxstripe** [StargateMC/StargateMCPublic#240]
http://peripheralsplusplus.readthedocs.io/en/latest/
adds blocks with more functionality (great along side computronics)

**Comment by PixelGamerX32** [comment]
I agree. It would help with using CC computers. Having to select a Computer to type and check on the monitor connected to it, is a pain.

**Comment by Bysokar** [comment]
Once we have a test server i'll let you guys try stuff like this out.
