### ISSUE TITLE
1.10.x Minecraft Update

### ISSUE THREAD

**Issue by Bysokar** [StargateMC/StargateMCPublic#241]
Below is a list of compatibility requirements for Minecraft 1.10.x.
It is purely used to track the progress of Minecraft 1.10.x's ability to become a StargateMC server.
This will utilize **Sponge** as a plugin platform, so all plugins must come from there or be developed for there.

Please do not make comments on this thread, other than to add mods/plugins/features to the list.

Plugins:
- [ ] World Management (and as many custom generators as possible)
- [ ] Permissions
- [ ] Player Claims & Relations
- [ ] Economy
- [ ] Scoreboard
- [ ] Universe (Will be developed for Sponge)
- [ ] Modded Block Protection (Assumedly this will be fine)
- [ ] Market

Mods:
- [ ] WarpDrive (Presently supports 1.7.10)
- [ ] SGCraft (Presently supports 1.7.10 for full functionality)
- [ ] CustomNPCs (Presently supports 1.9.0 (Beta))

**Comment by dodhod** [comment]
Galaticraft (Planets)
Flans Mod (Guns)
All the mods that add the blocks necessary for the custom builds
OC and CC

**Comment by dodhod** [comment]
Would be nice but not NEEDED:
MCHeli
Security Craft

**Comment by PixelGamerX32** [comment]
I have SecurityCraft Chests, won't they be affected if SecurityCraft is to be removed?
Also I like that they have CCTV cameras. Helps with montoring large bases.
