### ISSUE TITLE
Fluivac can place items in claimed land

### ISSUE THREAD

**Issue by dodhod** [StargateMC/StargateMCPublic#247]
Fluivac can place items on the ground In someone elses territory. This should be fixed.

**Comment by XredstonemodsX** [comment]
*Player takes ZPM* And it's a fluivac, doesn't need to be disabled, just needs to be fixed with sprotect

**Comment by Bysokar** [comment]
Please format your issues appropriately, do not create multiple in 1 ticket and do not use this system for communication. That's what discord is for.
