### ISSUE TITLE
WD Ship Core Turns to tnt when mined

### ISSUE THREAD

**Issue by Maxstripe** [StargateMC/StargateMCPublic#254]
When you mine a warpdrive ship core it turns into tnt and explodes no matter when you mine it
this turns ship salvage ops into ship blast ops and renders them uselesss

**Comment by PixelGamerX32** [comment]
Wow... that is a bummer. Guess salvaging a ship is out of the question for now.

**Comment by Bysokar** [comment]
I actually believe this is an intended mechanic - either that or the ship core can only be mined with the right tools.
If you think this is unfair perhaps report a bug/issue on the warp drive GitHub.
