### ISSUE TITLE
Timing Out

### ISSUE THREAD

**Issue by Mace-Windu1** [StargateMC/StargateMCPublic#257]
Whenever I logon everyone times out. It started when I turned on some buildcraft stirling engines to power my quarry. If no one else is on the server, then I get on for a few seconds before it times out however it won't let me turn off the engines.

**Comment by PixelGamerX32** [comment]
I have a similar problem. Chunks appear bad on and around X: 152 Z:560 Y:78 On P2Y-321. I can't even move somewhere else at all.

**Comment by Bysokar** [comment]
Should be fixed.

**Comment by Mace-Windu1** [comment]
Not fixed.

**Comment by PixelGamerX32** [comment]
Seems like this might be a problem. Is there anyway to fix this? Apart from deleting playerdata, though this could be the last resort if nothing works.

**Comment by PixelGamerX32** [comment]
Bysokar, Me an Mace believe that the problem is a bad chunk on and around X: 152 Z:560 Y:78 on P2Y-321. It may be a corrupted chunk. I was on that chunk when the server performed one of your scheduled restarts. No warning of it. Just a immediate disconnect. It may have caused the problem, or just made it worse.

**Comment by Mace-Windu1** [comment]
We believe that we can fix it if we can get people off the server, then I can get on and break the BC quarry. As long as no one else is on it will give me about 25 seconds at a time. It may take a few tries because it doesn't always accept my input.

**Comment by Mace-Windu1** [comment]
Diamond teleported me away from the chuck before i timed out, and I can now play without problems. However the chunk is still likely a problem.

**Comment by PixelGamerX32** [comment]
Yeah, it is. I can't do much except wait for someone to teleport me away from it. I just cannot figure out why it still won't regenerate or even load. It could be a bad chunk from the last server restart.

**Comment by Mace-Windu1** [comment]
Fixed by bysokar, planet backup used.
