### ISSUE TITLE
Timing out on P2Y-321... HELP ME PLEASE?!

### ISSUE THREAD

**Issue by PixelGamerX32** [StargateMC/StargateMCPublic#258]
I can;t seem to be ab;e to move anywhere anymore. I was on P2Y-321 when a server restart was called, Now I time out EVERYTIME. Chunks appear bad on and around X: 152 Z:560 Y:78 On P2Y-321. No chunks load near me. Only the chunk Im on. I can;t play anymore now. PLEASE HELP ME AND OTHERS WITH THIS PROBLEM!

**Comment by PixelGamerX32** [comment]
#257 #256 These have similar problems reported.

**Comment by Bysokar** [comment]
Should be fixed.
