### ISSUE TITLE
New WD nerfs

### ISSUE THREAD

**Issue by XredstonemodsX** [StargateMC/StargateMCPublic#259]
While some of the Nerfs were warranted, some just made it impossible. Increasing power was okay, maybe not by the percent you did but it's managable, the timer upgrade was also managable. However if anything the buffer of the core should have been raised to match the new power requirements
It is now physically impossible to have any large ship Such as an Alkesh jump anywhere because there is simply not enough power in the core.

**Comment by Bysokar** [comment]
There are no specifics in this issue at all.
What size ship are you talking about? How far are you trying to jump?

**Comment by XredstonemodsX** [comment]
The ship size is quite under 19k, my math isn't able to account for air and I round up the dim number to make sure to encompass my entire ship, and the price is 4 million eu for a simple 62 block jump forwards, the max in the core is 100k

**Comment by XredstonemodsX** [comment]
After fine tuning the dims it brought it down to 3.6 million, which is still impossible

**Comment by Bysokar** [comment]
And in hyperspace?

**Comment by Maxstripe** [comment]
Sokar.... It can't get to hyperspace... No one can. To get into hyperspace you need 10 mil power stored up

**Comment by Bysokar** [comment]
Then make a PR and fix it. Stop complaining.
