### ISSUE TITLE
Recipe for the Lantean Personal Shields

### ISSUE THREAD

**Issue by Bysokar** [StargateMC/StargateMCPublic#26]
Lantean Shields require a recipe.

Recipe: TBC

**Comment by Maxstripe** [comment]
t1 zpm with 2 ff area projectors on its sides
a= air
z= zpm
p= projector
aaa
pzp
aaa

mabye make em teired and the better the zpm in it the more damage it can take before running out of juice

**Comment by DraksterAU** [comment]
Tiers for a SGTech item will not happen I don't think.

I may replace it with another item purely made by me, though.... That could.

**Comment by Maxstripe** [comment]
or just make it craftable
