### ISSUE TITLE
I cannot access the Discord chat for StargateMC server... PLEASE HELP!!

### ISSUE THREAD

**Issue by PixelGamerX32** [StargateMC/StargateMCPublic#280]
I am having trouble trying to reconnect to the Discord chat for this server.
I was able to access it before Bysokar reset the planet dimension for P2Y-321.
Now I cannot rejoin the chat anymore. It disappeared from my chat servers list after the server terminated for the 'chunk bug' to be fixed. I have tried countless times to reconnect, but it refused to connect.
I have tried to connect via the Technic site's Discord widget shown here:
![discord chat feed widget](https://cloud.githubusercontent.com/assets/21307676/19220790/7c7bfa00-8e2d-11e6-8d2e-984792628fee.PNG)
I clicked 'Connect' but it then gave me this:
![error message invalid or expired invite](https://cloud.githubusercontent.com/assets/21307676/19220796/bab22b1e-8e2d-11e6-986a-aef8bd0c2f41.PNG)
I have also tried to get the invite code from the url of the page and manually pasting it in to my discord app to add the invite:
![invite code in url](https://cloud.githubusercontent.com/assets/21307676/19220806/053e1530-8e2e-11e6-8fc0-005c64925386.PNG)
Note: The highlighted text in the red circle above is the invite code.
But the same Red Error message appeared when I clicked join.
![error message invalid or expired invite in discord app](https://cloud.githubusercontent.com/assets/21307676/19220831/68c70d1e-8e2e-11e6-8c8b-aaf6b51ab5a1.PNG)

I don't know why this is happening or what else I can do to fix this. 
Bysokar, was I banned from the chat feed?
I don't know what else I can do. Does anyone else have this problem?
If anyone can help me resolve this please help. Thanks again.
- PixelGamerX32 (ign: GamerX64)
PS. this also affected my PM chats that were related to the StargateMC discord chat server.

**Comment by Bysokar** [comment]
https://discord.gg/FV76SKW

**Comment by PixelGamerX32** [comment]
Oh. Will this link work?

**Comment by PixelGamerX32** [comment]
IT WORKED! Thanks soo much Bysokar for the quick reply.
