### ISSUE TITLE
Mod Suggestion: Adventure Backpacks Mod

### ISSUE THREAD

**Issue by PixelGamerX32** [StargateMC/StargateMCPublic#282]
I have a mod suggestion. It is not exactly a storage mod, it is more of a extra inventory space mod.
Link: https://mods.curse.com/mc-mods/minecraft/225063-adventure-backpack
This mod allows for more stuff to be carried plus a crafting area built-in to the bag. Also you carry fluids like water and lava. 
This mod will otherwise allow us to carry more in our pockets. And also can carry up to 27 inventory spaces plus an extra 18 inventory slots. 
In total you can carry up to 45 more spaces in inventory slots, making the total inventory space up to 72 more inventory slots.
The backpack also carries a portable bed, in the form of a sleeping bag.
I recommend this as it is a better backpack mod than the ones that are in this mod-pack already.
Please consider this.

**Comment by Bysokar** [comment]
Sorry, I'm not willing to add a new mod specifically for storage. We have plenty of alternatives and additional 'backpack' style inventories for players adds complexity to the server's coding requirements I do not want to add.

**Comment by PixelGamerX32** [comment]
Fair enough. I'm just unsure which backpacks actually can carry anything at all @Bysokar .
But thanks for the quick reply. The mod was in beta after all. Could have caused server instability.
