### ISSUE TITLE
Nano helmet warpdrive bug

### ISSUE THREAD

**Issue by Maxstripe** [StargateMC/StargateMCPublic#29]
IC2:itemArmorNanoHelmet"=BreathingIC2
so the config says the nano helm lets you breath and i had air pouches in my inv...
went to space got died in like 30 seconds and lost all stuff and ship because of this bug (helmet didnt let me breath even tho config says it does)
lil help here?
timestamp of bug: shortly after 3:15pm eastern time
am now stuck on destiny due to lack of any items
died second time when bug spawned me in water above destiny

**Comment by Maxstripe** [comment]
update got back to milky attemping retrieval

**Comment by XredstonemodsX** [comment]
This is resolved, player was using the wrong air canisters for the Nano Helmet
