### ISSUE TITLE
Galaxy Spawn Plugin Teleportation Timing

### ISSUE THREAD

**Issue by recneps** [StargateMC/StargateMCPublic#30]
The current galaxy spawn plugin(makes you respawn within the galaxy) actually teleports you before you die - not after. This means that, essentially, you don't lose items on death, and any death markers from a minimap mod generate at the spawn.

**Comment by DraksterAU** [comment]
This will be replaced by a custom plugin which will be completed with the major overhaul - ETA on release is 1 week.
