### ISSUE TITLE
Kino misdials

### ISSUE THREAD

**Issue by Mace-Windu1** [StargateMC/StargateMCPublic#344]
The kino occasionally dials the wrong address. It dials the gate, but when you go through it is the wrong planet. The planet is always in the same galaxy so far. GamerX64 has also experienced this.

**Comment by Mace-Windu1** [comment]
Usually I am trying to dial a spawn planet. Most recently I have been dialing Destiny and get sent to D7J-700. Gamer was sent there also on his own dial.

**Comment by Bysokar** [comment]
This should be rectified. Let me know if it persists.
