### ISSUE TITLE
Earth Marketeer logic

### ISSUE THREAD

**Issue by Mace-Windu1** [StargateMC/StargateMCPublic#348]
The marketeers on earth no longer have any logic. I am not sure about the other marketeers in the universe.

**Comment by Bysokar** [comment]
Hi Mace,

Make a dialog called Marketeer Intro, with two command dialog options.

You can do this here : http://StargateMC.com/dialogeditor/

If you do that I can update the server immediately otherwise this will need to wait.

**Comment by Mace-Windu1** [comment]
What do I need to put as the command?

**Comment by Bysokar** [comment]
Fixed :)
