### ISSUE TITLE
Gates Dont Work In SP

### ISSUE THREAD

**Issue by Maxstripe** [StargateMC/StargateMCPublic#35]
gates dont work in sp even if the name is earth (or any other name in the system)
subspace recievers say outside known universe

**Comment by DraksterAU** [comment]
This will be resolved with the new universe system. Eta is 1-2 weeks.

**Comment by Maxstripe** [comment]
ok thx

**Comment by DraksterAU** [comment]
I've completed the Universe system. This bug will be fixed in the next major release in roughly a week.
