### ISSUE TITLE
Create /s stuck command

### ISSUE THREAD

**Issue by Maxstripe** [StargateMC/StargateMCPublic#38]
The /s stuck command will do the following;

- Find the closest unclaimed area that is not underwater/underlava and teleport the player there.
- This command will have a 2 minute warmup to prevent it being used as a means of escape from a players enemies... where the player cannot move.

**Comment by DraksterAU** [comment]
@mainesi please kill them.

I'll add the auicide command to the new galaxy spawn plugin.

**Comment by DraksterAU** [comment]
Ill add a /stuck command.

This will have a 60 minute cooldown and teleport the player to the nearest safe unclaimed area.
If a safe place cannot be found (all of space will be this) it will teleport the player to the nearest galaxy spawn.

There will be validation to prevent this being used unless the player is stuck.

**Comment by DraksterAU** [comment]
Command now does the following;

 1. Cooldown of 30 minutes.
 2. Warmup of 2 minutes.
 3. Only works in claimed land.
