### ISSUE TITLE
WD jumping timeout on planets

### ISSUE THREAD

**Issue by Biomech434** [StargateMC/StargateMCPublic#42]
#As it is i can not find an error log, as i believe that this is a server side issue and network timeouts. Requires more testing to find out the exact cause of this timeout

**Comment by Maxstripe** [comment]
It's server side
It times out if ship jumping is large
Use small craft on planets

**Comment by DraksterAU** [comment]
@Maxstripe How big times out the server?

**Comment by Maxstripe** [comment]
If it's a large ship? The entire server gets timed out
It's cause of claims as the server has to calculate were it can fit it away from a claim

**Comment by Maxstripe** [comment]
And we did test this. Taking off from 555 in milkyway with mains x-401 not a small ship
Every jump timed everyone out
It's in space now so jumping it around is safe

**Comment by Biomech434** [comment]
Mine was around 200 blocks under the max limit of 3000 blocks

**Comment by Maxstripe** [comment]
We got mains exactly at the limit and it still caused issues
Keep below 1500 on a planet if possible

**Comment by DraksterAU** [comment]
Any issues jumping around space after that?

**Comment by Biomech434** [comment]
Not that i could tell

**Comment by DraksterAU** [comment]
This issue was caused by SRegen trying to log every break/place event a ship jump did. I've since updated it to fix this issue.
