### ISSUE TITLE
Add a new custom permission node to factions for GDO use

### ISSUE THREAD

**Issue by XredstonemodsX** [StargateMC/StargateMCPublic#43]
So currently, when you install a stargate reprogrammer, it allows only for you to dial in, short of a computer system, I want to have a way where you can use the code that the gate gives you when you install the repogrammer upgrade in other GDOs, to allow your allies and faction members access to your gate w/o using more than the default GDO/Reprogrammer combination

**Comment by DraksterAU** [comment]
There is a whitelist you can access via the computer interfaces to add new players to be allowed to use GDOs.

Without a computer interface it only works for the person who reprogrammed it.

**Comment by DraksterAU** [comment]
Actually I'll look into a faction perm for this.

**Comment by Maxstripe** [comment]
Does the comp need to be running all the time for us whitelist to work or is it program in and leave

**Comment by DraksterAU** [comment]
I might get the interface to handle it.

**Comment by DraksterAU** [comment]
Interface handles this. As long as the interface is active the computer can be disconnected.
