### ISSUE TITLE
Casting a fishing line into a stargate crashes the server

### ISSUE THREAD

**Issue by Maxstripe** [StargateMC/StargateMCPublic#46]
So going fishing in a stargate crashes the server 
Might wanna ban fishing rods
Or find out why it does this

**Comment by DraksterAU** [comment]
The line is an entity. It can't return.

I'll fix it - we can just get Stargates to not attempt to teleport fishing line.

**Comment by Maxstripe** [comment]
Ok
Also mind adding like a staff vote restart so if 75% of the staff or more feel it needs a restart we can do that

**Comment by DraksterAU** [comment]
Restarts are handled via admins at the moment.

I'll add something to automatically restart the server if we get 0 TPS for a set amount of time though.

Breaking blocks not working seems a bit odd.

**Comment by Maxstripe** [comment]
Yup well  the crash fixed that issue
So just look within minutes before the crash and you know when everything was wacky
Or just look when we were talkng before the crash that's better for pinpointing it
