### ISSUE TITLE
Zero Point Modules are missing recipes

### ISSUE THREAD

**Issue by Bysokar** [StargateMC/StargateMCPublic#49]

**Comment by DraksterAU** [comment]
So far I've got the Containment Chamber item for this. otherwise, I'm not sure what the shell should be made out of. More Sunnaranium?

**Comment by Maxstripe** [comment]
what mods can we use items from for custom recipies?
ik we cant use ae2 what else?

**Comment by DraksterAU** [comment]
Nothing else...

**Comment by Maxstripe** [comment]
O ok then
Crude zpm could be shitty 
T - transformer
A - advanced machine casing
U - uu cell
Z - zpm core

ATA
UZU
  U

normal zpm
M - mass fab
T - teleporter
U - uu cell
H - hv transformer
Z - zpm core
MHM
 TZT
   U

ENHANCED - require a normal zpm with no entropy and have it surrounded either by lapotronic crystals and iridium plates like 
LIL
IZI
LIL
or an Mfsu lap crystals and iridium plates like 
LML
IZI
LIL
or just surround it with iridium plates
III
IZI
III

**Comment by Biomech434** [comment]
What would the enhanced do or have over the normal? What would the crude one look like and how much power? How is the core made or is it already in NEI, or is it discover able in world.
I think that for the zpm core an extra step should be in their, putting the ZPM core( with no connection too vacuum space) in the molecular transformer for a certain amount of power to say make the connection to vacuum space, but not making it too ridiculous in the amount of energy.

**Comment by Maxstripe** [comment]
sokar last i checked all zeds had recipes. this shouldnt be needed anymore
