### ISSUE TITLE
Gates will not get a lock

### ISSUE THREAD

**Issue by XredstonemodsX** [StargateMC/StargateMCPublic#53]
Title says it all. Gates will dial to chev 8, and then cancel at 9

**Comment by DraksterAU** [comment]
This is due to power requirements being too high for a lock.

At present a gate requires 10x the 1sec cost for a wormhole upon connection and then 1x the 1sec cost per second after that.

The initial check is done on 1x1 not 10x1.

Going to reduce power required by about 75% tonight.

**Comment by DraksterAU** [comment]
This has been fixed in a previous update. Gates now check for the right amount of power before dialling rather than dial and then fail at the end because it hasn't got the power available.
