### ISSUE TITLE
Warp Drive Landed In Faction Land

### ISSUE THREAD

**Issue by Maxstripe** [StargateMC/StargateMCPublic#58]
Warp drives current dont land in faction protected land thing is based on warpdrive checking the landing zone
but when jumping down from space as i did it cant see the landing zone because spaece jump downs are seen as going below zero
so it jumps and ends up placed in faction land and cant jump back out since comp perm isnt set for truce
basicly coming from space doesnt broadcast faction status of land beneath

**Comment by DraksterAU** [comment]
This is resolved in a recent update.
Will be pushing this over the weekend.

**Comment by DraksterAU** [comment]
This is fixed in the current WD build
