### ISSUE TITLE
Readd Support for Midway

### ISSUE THREAD

**Issue by Biomech434** [StargateMC/StargateMCPublic#59]
Just recently i just visited midway and the kino and the dialing computer for atlantis do not work. 
Is the kino not supposed to work on mid way? I think that the dialing computer may need to be change to something more stable or the program needs to be updated.

**Comment by DraksterAU** [comment]
Midway hasn't really been thought of recently. Ill look at this this week.

**Comment by DraksterAU** [comment]
Midway support needs to be reinstated:

- [ ] Computer program
- [ ] Gate dialling mechanics
