### ISSUE TITLE
Gates power bugs and death problems

### ISSUE THREAD

**Issue by Maxstripe** [StargateMC/StargateMCPublic#60]
So gates still have the power issue I get that but the gate on dim-331 seems to be able to dial my base (Milky Way) but not a destiny gate
Even tho it is in destiny
Also mind putting keep inv on for now since gates don't work and when you die your stuff drops and you loose it since you can't get back home

**Comment by DraksterAU** [comment]
1. GalaxySpawn is now functional. So that should stop that from now on.
2. Keep inventory is not going to be enabled.
3. Ive reduced the power requirements for gates by 90%... and will soon enable unlimited power on official gates for same galaxy dialling.
