### ISSUE TITLE
Make Spawn Worlds capable of intergalactic dials

### ISSUE THREAD

**Issue by Maxstripe** [StargateMC/StargateMCPublic#62]
So Destinys spawn gate (the ship) is incapable of intergalactic
cant dial lantea or earth
pretty sure the other spawns cant do intergalactic too

**Comment by DraksterAU** [comment]
Spawns will not have free access to other galaxies anymore. Instead we will make it so that they have the necessary upgrades and can sometimes do it. Perhaps with a players help (player provided ZPM etc).

**Comment by Maxstripe** [comment]
ok then

**Comment by Biomech434** [comment]
Is the ship transport still a feature with the server or not?If so you could get to different galaxy that way or with your own ship.

**Comment by DraksterAU** [comment]
It will be !

**Comment by Biomech434** [comment]
Ummm ok then. What will  be?

**Comment by DraksterAU** [comment]
I meant different galaxies via ships like the Daedalus.

Not going to prevent flying your own ship elsewhere - though I'm keen on making ships have to consist of actual ship hulls etc.

**Comment by Maxstripe** [comment]
They do need to be sealed if you want air
And accual hull if you want armor
Otherwise it's very easy to explode
