### ISSUE TITLE
Arena Events (time travel, Earth)

### ISSUE THREAD

**Issue by mbacookie** [StargateMC/StargateMCPublic#67]
A new arena event.

The player is placed in the bottom of chayene mountain and must leave the mountain and find the stargate in order to dial home.

This is subject to a time restraint (5 mins?) in which if the player does not find the gate, they die.

This can possibly be made harder if we can make the gate randomly generate in a military building every game so that it is not in the same place all the time

**Comment by Maxstripe** [comment]
sounds nice 
i second this

**Comment by DraksterAU** [comment]
Procedurally generating a map is hard. And once players know the path to the gate, it will be useless.
I do like the idea of time travel, but for now we'll skip that as it would be as complicated as the NPC plugin I just finished, if not more........ If we get more devs I'll happily look into it.
