### ISSUE TITLE
wind generators from mekanism and tesseracts 

### ISSUE THREAD

**Issue by matty705** [StargateMC/StargateMCPublic#68]
When placing a wind generator directly next to a tesseract so that the power will flow into it with no cables in between the server crashes..

**Comment by mbacookie** [comment]
Tesseracts were disabled by sokar
As for the server crash maybe we should remove them as craftable for now to stop people using them

**Comment by Biomech434** [comment]
Wait, tesseracts are disabled? Do the mekanisim equivalent take its place?

**Comment by Maxstripe** [comment]
correction: they are not disabled as of yet but they will be
issue with tehm not working with TE is a bug just dont do it

**Comment by DraksterAU** [comment]
Update to TE fixes this. Aidan provided me with the versions he has working with Mek 9

**Comment by DraksterAU** [comment]
This is resolved with the Thermal mod updates.
