### ISSUE TITLE
Open Security and mod pack

### ISSUE THREAD

**Issue by Biomech434** [StargateMC/StargateMCPublic#69]
Currently the mod pack (FML) wants to download this mod from this site, http://caitlynmainer.com/OpenSecurity/klaxon2.ogg, and it cant, so it directs me to the page so that i can manually download it. As it is the website to download is currently unavailable. So any suggestions?

**Comment by DraksterAU** [comment]
Fixed with https://github.com/StargateMC/StargateMCPublic/commit/acd7efa1541f546e2316e994e1a108740b664bce on server side. Will push to client shortly.
