### ISSUE TITLE
Warp drive radar not registering nearbye ships 

### ISSUE THREAD

**Issue by Maxstripe** [StargateMC/StargateMCPublic#73]
Warp drive radar doesn't restister nearby ships since this update even if the ship is right next to it 
Did you change wD

**Comment by DraksterAU** [comment]
Didn't change any thing. If it doesn't do it now it never did.

**Comment by Maxstripe** [comment]
It worked before the update 
I used it a lot

**Comment by Maxstripe** [comment]
nvrmnd im an idiot
it only works in space
