### ISSUE TITLE
Forcefields can be breached with a tube projector from the outside

### ISSUE THREAD

**Issue by DraksterAU** [StargateMC/StargateMCPublic#74]
At present a well placed Tube projector outside a forcefield can be used to breach it.
A good workaround would be to require the tube projector sit inside the active forcefield in order to breach it.
Alternatively, having forcefields operate on a frequency and a frequency match being required would also work.

**Comment by DraksterAU** [comment]
@immibis Any chance you could look into this?

**Comment by Biomech434** [comment]
Well, the inhibitor upgrade is meant to prevent any force field that is interacting, like the tube projector, with the other field. 
Here is the wiki with the information on the mod specifying all of the abilities of the addon.
http://forum.industrial-craft.net/index.php?page=Thread&postID=65261

**Comment by Maxstripe** [comment]
then we gotta off the inhibtor upgrade too
otherwise why bother putting sheilds ona structure at all?

**Comment by Biomech434** [comment]
the inhibitor upgrade prevents other enemy shields from entering in. Theyou tube video has a more in depth explanation.

**Comment by DraksterAU** [comment]
It prevents fields from different cores which are activated after the one with the inhibitor from appearing inside the field it's attached to. Only works on area projectors.

Using an inhibitor upgrade on your forcefield prevents tube projectors from another forcefield core from interacting with (or cutting into) your forcefield. Unbanning the item.
