### ISSUE TITLE
Create tickable NPC "Events"

### ISSUE THREAD

**Issue by DraksterAU** [StargateMC/StargateMCPublic#75]
NPCs need to be able to follow a scripted event style scenario, ideally being able to check if a player has completed certain quests or is one certain quests also.

This will benefit the server in a myriad of ways... such as:

- Walter Harriman controlling the Stargate Iris / Stargate on Earth
- Randomised Incursion events where randomised NPCs dial a stargate and travel through... to attack or trade with whoever is on the other side.
- Random spawning NPCs that are themed based on galaxy (i.e Wraith or Athosians for Pegasus, Jaffa for Milky way).. these will spawn reasonably commonly. They will be both hostile and friendly.
- Random scenario based encounters in-game. Such as Crashed wraith hives, Tauri Outposts that repeatedly fall under attack etc.
- Scripted Transportation events that allow the main ships in the SG Universe (eg: Daedalus) to actually transport players between galaxies.

**Comment by Biomech434** [comment]
These things sound great. Lots more features to add

**Comment by DraksterAU** [comment]
It's one feature. But a major one.
