### ISSUE TITLE
Leader removal of faction

### ISSUE THREAD

**Issue by Biomech434** [StargateMC/StargateMCPublic#77]
When i got on about 20 min ago i found out that i had been removed from my faction. As off right now i do not know the cause. What i do know is that the Synergists faction is leaderless and i dont know why that i have been removed from it. Any info would be enlightening as to weather this is a bug or just me.

**Comment by DraksterAU** [comment]
What is your IGN?

**Comment by Biomech434** [comment]
I am sorry what is IGN?

**Comment by Biomech434** [comment]
OBwon1424

**Comment by DraksterAU** [comment]
How long were you offline for?

**Comment by Biomech434** [comment]
1 Day

**Comment by Biomech434** [comment]
Can having a low power kick a player from the faction?

**Comment by DraksterAU** [comment]
No... It shouldn't. I'll have a look tonight.

Be online in 10-12 hours if you can.
Or 7hoirs from now.

**Comment by Biomech434** [comment]
Ill see if i am up at that time as i have MST/MDT

**Comment by DraksterAU** [comment]
This should be fixed..
