### ISSUE TITLE
D1X-209

### ISSUE THREAD

**Issue by XredstonemodsX** [StargateMC/StargateMCPublic#78]
The ocean planet D1X-209 is no longer able to be dialed to or from, the planet is populated in Suniverse and in Warp Drive.

**Comment by DraksterAU** [comment]
What is the message you get when you try to dial there? Or does it not appear in the kino?

**Comment by mainesi** [comment]
it is not part of the known universe. bit like tollana was before we added it to the network of gates

**Comment by DraksterAU** [comment]
Put in a PR to move it closer to the universal centre.. But still within the destiny Galaxy.
Or a PR to increase the space world border in SWorlds and SUniverse
