### ISSUE TITLE
NPC's should have multiple spawn points

### ISSUE THREAD

**Issue by XredstonemodsX** [StargateMC/StargateMCPublic#85]
This would be beneficial for NPC's like Atlantis Guard which need multiple spawn points to actually guard for atlantis

**Comment by XredstonemodsX** [comment]
How I think it would have is the first would be mandatory if randomSpawn = false

and the next could be copy/pasted lines such as done for the drop list

**Comment by DraksterAU** [comment]
Nah I'm going to handle guard style npcs with the random spawn code.

Will explain further in 1hr

**Comment by DraksterAU** [comment]
@XredstonemodsX So I'm thinking... rather than random spawn for unclaimed areas, I focus on making ClonedList work.

Then we can define places wraith spawn, or friendlies..... rather than have so much load placed on the server for completely randomised everything.

What do you think?

**Comment by XredstonemodsX** [comment]
Would make farming Wraith Scientists easier, which could lead to making ZPM farms. other than that it seems an okay idea

**Comment by DraksterAU** [comment]
I've figured out how to sort out random spawns.
Should be ok.

Remember all npcs despawn on restart so a farm would have little benefit.

**Comment by DraksterAU** [comment]
clonedlist supports this now.
