### ISSUE TITLE
Gate Computer Interface Crystal Wipe

### ISSUE THREAD

**Issue by Maxstripe** [StargateMC/StargateMCPublic#93]
Gate Computer Interfaces wipe upgrade crystals input within

**Comment by DraksterAU** [comment]
When? If you break the block do they drop?

**Comment by Maxstripe** [comment]
They drop if you break it during the same day you placed it
After 24 hours it wiped the crystals for some reason (same thing happened at spawn this just confirms it)

**Comment by DraksterAU** [comment]
I believe I just fixed this. The writeToNBTData function to save this data on chunk unload wasn't correct. Releasing an update now. Reopen this issue if it persists.
